# tryagain

retry_call(
    function=some_function,
    exceptions=Exception,
    max_attempts=None,
    pre_call_hook=None,
    after_exception_hook=None)
